# Generated by Django 4.2.15 on 2024-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcallinfo',
            name='vote',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], null=True),
        ),
    ]
