# Generated by Django 4.2.15 on 2024-08-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotModel',
            fields=[
                ('bot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('TYPE', models.CharField(max_length=1)),
                ('CODE', models.CharField(help_text='Строковый идентификатор бота', max_length=255)),
                ('EVENT_MESSAGE_ADD', models.URLField(help_text='Обработчик входящих сообщений', max_length=500)),
                ('EVENT_WELCOME_MESSAGE', models.URLField(help_text='Обработчик приветствия, начало работы', max_length=500)),
                ('EVENT_BOT_DELETE', models.URLField(help_text='Обработчик запроса об удалении чат бота', max_length=500)),
                ('NAME', models.CharField(help_text='Имя бота', max_length=255)),
                ('LAST_NAME', models.CharField(help_text='Фамилия Бота', max_length=255)),
                ('EMAIL', models.EmailField(help_text='Введите email, не совпадает с адресами настоящих пользователей', max_length=255)),
                ('COLOR', models.CharField(max_length=50)),
                ('PERSONAL_BIRTHDAY', models.DateField(help_text='День рождения')),
                ('WORK_POSITION', models.TextField(help_text='Описание чат-бота')),
                ('PERSONAL_WWW', models.URLField(help_text='Ссылка на сайт', max_length=500)),
                ('PERSONAL_GENDER', models.CharField(max_length=1)),
                ('PERSONAL_PHOTO', models.ImageField(blank=True, default='default.jpg', upload_to='bot_photo/')),
            ],
        ),
    ]
