# Generated by Django 4.2.15 on 2024-08-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioToTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voices')),
                ('description', models.TextField(blank=True, help_text='Выберите аудио файл, только mp3/wav', null=True)),
                ('text_of_file', models.TextField(blank=True, null=True)),
                ('choose_model', models.CharField(choices=[('tiny.en', 'Tiny En'), ('tiny', 'Tiny'), ('base.en', 'Base En'), ('base', 'Base'), ('small.en', 'Small En'), ('small', 'Small'), ('medium.en', 'Medium En'), ('medium', 'Medium'), ('large-v1', 'Large V1'), ('large-v2', 'Large V2'), ('large-v3', 'Large V3'), ('large', 'Large')])),
            ],
        ),
    ]
